import operator
from collections.abc import Callable
from typing import Annotated, Any, TypedDict

from satquery.agent.task_enum import Task
from satquery.agent.trace import TraceBuilder
from satquery.ingest.band_inventory import BandInventory


class AssetRef(TypedDict):
    """Reference to an asset generated by a tool."""
    kind: str
    path: str
    description: str | None


class PlannedStep(TypedDict):
    """A tool invocation planned by the agent."""
    tool: str
    params: dict[str, Any]
    within_manifest: bool
    depends_on: list[str] | None


class ToolResult(TypedDict):
    """The result of executing a tool."""
    outputs: dict[str, Any]
    confidence: float
    latency_ms: int


class AgentState(TypedDict):
    """
    The state dictionary threaded through the LangGraph controller.
    Fields annotated with `operator.add` are appended to rather than overwritten.
    """
    query_id: str
    query_text: str
    bundle: Any  # ImageBundle
    band_inventory: BandInventory
    modalities: list[str]
    pair_type: str
    allow_llm_router: bool

    task: Task | None
    router_path: str | None  # "rules" | "llm"
    routing_notes: Annotated[list[str], operator.add]

    validation_ok: bool
    refusal: dict[str, str] | None
    tile_plan: Any | None  # TilePlan

    plan: list[PlannedStep]
    gate_passed: bool
    gate_rejected: list[str]
    replan_count: int

    results: dict[str, ToolResult]
    agreement: dict[str, Any] | None
    fused_answer: str | None
    confidence: float | None
    confidence_basis: str | None

    assets: Annotated[list[AssetRef], operator.add]
    warnings: Annotated[list[str], operator.add]

    trace: TraceBuilder
    emit: Callable[[str, dict[str, Any]], None]
    timings: dict[str, int]
